(function() {var implementors = {};
implementors['rusoto'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='rusoto/error/struct.AWSError.html' title='rusoto::error::AWSError'>AWSError</a>&gt; for <a class='struct' href='rusoto/dynamodb/struct.DynamoDBError.html' title='rusoto::dynamodb::DynamoDBError'>DynamoDBError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='rusoto/error/struct.AWSError.html' title='rusoto::error::AWSError'>AWSError</a>&gt; for <a class='struct' href='rusoto/ecs/struct.ECSError.html' title='rusoto::ecs::ECSError'>ECSError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://lifthrasiir.github.io/rust-chrono/chrono/format/struct.ParseError.html' title='chrono::format::ParseError'>ChronoParseError</a>&gt; for <a class='struct' href='rusoto/error/struct.AWSError.html' title='rusoto::error::AWSError'>AWSError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>IoError</a>&gt; for <a class='struct' href='rusoto/error/struct.AWSError.html' title='rusoto::error::AWSError'>AWSError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='rusoto/xmlutil/struct.XmlParseError.html' title='rusoto::xmlutil::XmlParseError'>XmlParseError</a>&gt; for <a class='struct' href='rusoto/error/struct.AWSError.html' title='rusoto::error::AWSError'>AWSError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='rusoto/error/struct.AWSError.html' title='rusoto::error::AWSError'>AWSError</a>&gt; for <a class='struct' href='rusoto/kms/struct.KMSError.html' title='rusoto::kms::KMSError'>KMSError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/core/num/struct.ParseIntError.html' title='core::num::ParseIntError'>ParseIntError</a>&gt; for <a class='struct' href='rusoto/xmlutil/struct.XmlParseError.html' title='rusoto::xmlutil::XmlParseError'>XmlParseError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
